II.26

In [2]:
import numpy as np
rnd = np . random . RandomState (1234)
n = 10
A = rnd . uniform ( size =( n , n )) + np . diag ([15]* n )
b = rnd . uniform ( size = n )

In [3]:


D = np.diag(np.diag(A))

B = np.linalg.inv(D) @ (D - A)

c = np.linalg.inv(D) @ b

np.linalg.norm(B), np.linalg.norm(A)

(0.36436161983015336, 49.25240171558933)

In [4]:
x0 = rnd . uniform ( size = n )
eps = 1
niter = 0
maxiter = 100
while True:
    niter += 1
    x = B @ x0 + c
    if np.linalg.norm(x - x0)/np.linalg.norm(x) < eps or niter > maxiter:
        break
    x0 = x
x

array([ 0.0441097 ,  0.04202545,  0.04693011,  0.0287482 ,  0.06004829,
        0.00380659, -0.00311671,  0.03503543,  0.0001325 ,  0.05662161])

In [5]:
np.linalg.solve(A,b)

array([ 0.03919429,  0.03780037,  0.04283232,  0.02365951,  0.05745031,
       -0.00030244, -0.00577279,  0.03177549, -0.00422849,  0.05284648])

Уменьшим величину диагональных элементов

In [6]:
S = rnd . uniform ( size =( n , n )) + np . diag ([4]* n )

In [7]:
np.linalg.norm(S)

DS = np.diag(np.diag(S))

BS = np.linalg.inv(DS) @ (DS - S)

cS = np.linalg.inv(DS) @ b

np.linalg.norm(BS)

1.2726608306515448

In [8]:
x0 = rnd . uniform ( size = n )
eps = 1
niter = 0
maxiter = 100
while True:
    niter += 1
    x = BS @ x0 + cS
    if np.linalg.norm(x - x0)/np.linalg.norm(x) < eps or niter > maxiter:
        break
    x0 = x
x

array([-147.2610198 , -147.8027703 , -138.17928741, -279.45843397,
       -237.79074927, -204.6078051 , -198.17436423, -211.13145985,
       -241.19756198, -169.23806962])

In [9]:
np.linalg.solve(S,b)

array([ 0.09343014,  0.11700538,  0.14470933,  0.05461214,  0.12949954,
       -0.03318014, -0.08901233,  0.10732762, -0.08960466,  0.14310221])

Видно, что при уменьшении преобладания диагональных элементов результаты становятся сильно неточными

Это объясняется тем, что норма матрицы В стала больше 1

III.3

In [10]:
maxiter=100
eps=1e-5    
x0 = 1 #prev
x = np.zeros_like(x0) #cur
it = 0
while True:
    it += 1
    x = x0 + (np.cos(x0)+1)/np.sin(x0)
    if np.abs(x - x0)/np.abs(x) < eps or it > maxiter:
        break
    x0 = x
x, it

(3.141573869728747, 15)

In [11]:
maxiter=100
eps=1e-5    
x0 = 1 #prev
x = np.zeros_like(x0) #cur
it = 0
while True:
    it += 1
    x = 1/2 * (x0 + 2/x0)
    if np.abs(x - x0)/np.abs(x) < eps or it > maxiter:
        break
    x0 = x
x, it

(1.4142135623746899, 4)

Видно, что во втором случае, количество операций меньше в it раз.

III.4

III.5

In [33]:
def func(X):
    x, y = X
    return np.array([x**3 - 3.0*x*y**2 - 1.0,
                     3.0*x**2*y - y**3])

def jac(X):
    x, y = X
    return np.array([[3.*x**2 - 3*y**2, -6*x*y],
                     [6*x*y, 3*x**2 - 3*y**2]])

In [34]:
def newton_system(F, jcb, X0, eps=1e-5, maxiter=100):
    X = X0
    niter = 0
    while True:
        X =  np.linalg.solve(jcb(X),  jcb(X) @ X - F(X))
        niter += 1
        if np.linalg.norm(X - X0) < eps or niter > maxiter:  
            break
    
    return X, niter

In [35]:
import time
from tqdm import tqdm
coordinates = np.zeros((400,400))
results = np.zeros((400,400))
for i in range(400):
    for j in range (400):
        x = i*3/400 - 1.5
        y = j*3/400 - 1.5
        root = newton_system(func, jac, np.array([x, y]))[0]
        coordinates[i] = x
        coordinates[j] = y
        if 2 * root[0] < root[1] and root[1] > 0:
            results[i][j] = 1
        else:
            if root[0] >= np.abs(root[1]/2):
                results[i][j] = 0
            else:
                results[i][j] = 2
results

LinAlgError: Singular matrix

In [ ]:
import matplotlib

In [ ]:
from matplotlib import pyplot as plt 

In [ ]:
plt.plot()